POST http://localhost:3000/groups HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJ1bGxvY2tzMTIzIiwiaWF0IjoxNjQ2MzQyNjY3LCJleHAiOjMyOTMwNDUzMzQsImlzcyI6ImFtYXppbmdfaXNzdWVyIn0.QjKVKq3FmdfCmyiSroWIBah_DyvvM1hZnUhBXs6mVXE

{
    "name": "clients",
    "permissions": ["READ"]
}

###
POST http://localhost:3000/groups HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJ1bGxvY2tzMTIzIiwiaWF0IjoxNjQ2MzQyNjY3LCJleHAiOjMyOTMwNDUzMzQsImlzcyI6ImFtYXppbmdfaXNzdWVyIn0.QjKVKq3FmdfCmyiSroWIBah_DyvvM1hZnUhBXs6mVXE

{
    "name": "sellers",
    "permissions": ["READ", "WRITE", "UPLOAD_FILES"]
}

###
###
POST http://localhost:3000/groups HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJ1bGxvY2tzMTIzIiwiaWF0IjoxNjQ2MzQyNjY3LCJleHAiOjMyOTMwNDUzMzQsImlzcyI6ImFtYXppbmdfaXNzdWVyIn0.QjKVKq3FmdfCmyiSroWIBah_DyvvM1hZnUhBXs6mVXE

{
    "name": "admin",
    "permissions": ["READ", "WRITE", "UPLOAD_FILES", "DELETE", "SHARE"]
}

###
POST http://localhost:3000/groups HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJ1bGxvY2tzMTIzIiwiaWF0IjoxNjQ2MzQyNjY3LCJleHAiOjMyOTMwNDUzMzQsImlzcyI6ImFtYXppbmdfaXNzdWVyIn0.QjKVKq3FmdfCmyiSroWIBah_DyvvM1hZnUhBXs6mVXE

{
    "name": "ERROR_GROUP_TEST",
    "permissions": ["BULLOCKS"]
}

###

GET http://localhost:3000/groups HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/groups/cbcc7b73-add0-49cf-89d5-5b71ef70be74 HTTP/1.1
content-type: application/json

###

PATCH  http://localhost:3000/groups/5a1c8cf2-632d-4476-8a68-01a8b97dc2ae HTTP/1.1
content-type: application/json

{
    "permissions": ["READ", "SHARE"]
}

###

###

DELETE  http://localhost:3000/groups/05babbc9-18cc-4500-9d9d-90d5c268d8ca HTTP/1.1
content-type: application/json