POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "login": "aaa01212",
    "password": "123",
    "age": 45
}

###

GET http://localhost:3000/users/123456 HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/users HTTP/1.1
content-type: application/json

###

###

GET http://localhost:3000/users?pattern=12&order=asc&limit=3 HTTP/1.1
content-type: application/json

###

PATCH  http://localhost:3000/users/123456 HTTP/1.1
content-type: application/json

{
    "isDeleted": false
}

###

DELETE  http://localhost:3000/users/123456 HTTP/1.1
content-type: application/json
