POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "login": "aaa0",
    "password": "123",
    "age": 45,
}

###

GET http://localhost:3000/users/123456 HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/users HTTP/1.1
content-type: application/json

###

###

GET http://localhost:3000/users HTTP/1.1
    ?pattern=12
    &order=desc
    &limit=1 
content-type: application/json

###

PATCH  http://localhost:3000/users/458feaec-dbd1-4df8-9f0f-d39bce01c3e4 HTTP/1.1
content-type: application/json

{
    "isDeleted": false
}

###

DELETE  http://localhost:3000/users/458feaec-dbd1-4df8-9f0f-d39bce01c3e4 HTTP/1.1
content-type: application/json
