POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "login": "Edu",
    "password": "123aaa",
    "age": 25
}

###

GET http://localhost:3000/users/dab5e828-952d-40c7-9fe4-7bb786e467ab HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/users HTTP/1.1
content-type: application/json

###

###

GET http://localhost:3000/users?pattern=B&order=asc&limit=5 HTTP/1.1
content-type: application/json

###
###

GET http://localhost:3000/users?pattern=B&order=desc&limit=5 HTTP/1.1
content-type: application/json

###

###

GET http://localhost:3000/users?limit=5 HTTP/1.1
content-type: application/json

###

PATCH  http://localhost:3000/users/3TDZRreq5hu HTTP/1.1
content-type: application/json

{
    "isDeleted": false
}

###

DELETE  http://localhost:3000/users/dab528-952d-40c7-9fe4-7bb786e467ab HTTP/1.1
content-type: application/json
